global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:4040"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]

  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra:9042"]
